// 🌞 DAILY CONTENT — jokes, riddles, quotes, and words of the day
// ✏️ SEBASTIAN: You can add your own jokes and riddles here!

export const jokes = [
  { q: "Why did the creeper cross the road?", a: "to get to the other side", display: "To get to the other SSSSSIDE! 💥" },
  { q: "What do you call a pig that knows karate?", a: "pork chop", display: "A pork chop! 🐷" },
  { q: "Why can't Elsa hold a balloon?", a: "let it go", display: "Because she'll LET IT GO! 🎈" },
  { q: "What do you call a dinosaur that crashes their car?", a: "tyrannosaurus wrecks", display: "Tyrannosaurus WRECKS! 🦖" },
  { q: "Why did the teddy bear say no to dessert?", a: "stuffed", display: "Because she was already STUFFED! 🧸" },
  { q: "What do you call a fish without eyes?", a: "fsh", display: "A fsh! 🐟" },
  { q: "Why do bees have sticky hair?", a: "honeycomb", display: "Because they use HONEYcombs! 🐝" },
  { q: "What do you call a sleeping dinosaur?", a: "dino snore", display: "A dino-SNORE! 😴" },
  { q: "Why did the Minecraft player bring a ladder?", a: "next level", display: "To get to the NEXT LEVEL! 🎮" },
  { q: "What's a Lego's favorite music?", a: "block and roll", display: "Block and roll! 🧱" },
  { q: "What do you call cheese that isn't yours?", a: "nacho cheese", display: "Nacho cheese! 🧀" },
  { q: "Why don't eggs tell jokes?", a: "crack up", display: "They'd crack up! 🥚" },
  { q: "What do you call a bear with no teeth?", a: "gummy bear", display: "A gummy bear! 🐻" },
  { q: "Why did the scarecrow win an award?", a: "outstanding", display: "Because he was OUTSTANDING in his field! 🌾" },
  { q: "What do you call fake spaghetti?", a: "impasta", display: "An impasta! 🍝" },
  { q: "Why couldn't the bicycle stand up?", a: "two tired", display: "It was two-tired! 🚲" },
  { q: "What do you call a dog that can do magic?", a: "labracadabrador", display: "A Labracadabrador! 🐕✨" },
  { q: "Why don't scientists trust atoms?", a: "make up everything", display: "Because they make up everything! ⚛️" },
  { q: "What do you call a sleeping bull?", a: "bulldozer", display: "A bulldozer! 🐂" },
  { q: "Why did the golfer bring two pairs of pants?", a: "hole in one", display: "In case he got a hole in one! ⛳" },
  { q: "What do you call a snowman with a six pack?", a: "abdominal", display: "An abdominal snowman! ⛄💪" },
  { q: "Why did the tomato turn red?", a: "saw salad dressing", display: "Because it saw the salad dressing! 🍅" },
  { q: "What do you call a seagull that flies over the bay?", a: "bagel", display: "A bagel! 🥯" },
  { q: "Why did the cookie go to the doctor?", a: "crummy", display: "Because it felt crummy! 🍪" },
  { q: "What do you call a lazy kangaroo?", a: "pouch potato", display: "A pouch potato! 🦘" },
  { q: "Why don't skeletons fight each other?", a: "guts", display: "They don't have the guts! 💀" },
  { q: "What do you call an alligator in a vest?", a: "investigator", display: "An investigator! 🐊" },
  { q: "Why did the math book look sad?", a: "too many problems", display: "It had too many problems! 📚" },
  { q: "What do you call a bee that can't make up its mind?", a: "maybe", display: "A maybe! 🐝" },
  { q: "Why did the orange stop rolling?", a: "ran out of juice", display: "It ran out of juice! 🍊" },
  { q: "What do you call a boomerang that doesn't come back?", a: "stick", display: "A stick! 🪃" },
  { q: "Why did the banana go to the doctor?", a: "peeling", display: "It wasn't peeling well! 🍌" },
  { q: "What do you call a dinosaur with an extensive vocabulary?", a: "thesaurus", display: "A thesaurus! 📖" },
  { q: "Why did the music teacher go to jail?", a: "sharp", display: "Because she got caught with a sharp! 🎵" },
  { q: "What do you call a cow on a trampoline?", a: "milk shake", display: "A milk shake! 🐄" },
  { q: "Why did the photo go to jail?", a: "framed", display: "It was framed! 📸" },
  { q: "What do you call a sheep with no legs?", a: "cloud", display: "A cloud! ☁️" },
  { q: "Why did the computer go to the doctor?", a: "virus", display: "It had a virus! 💻" },
  { q: "What do you call a fish that wears a crown?", a: "king fish", display: "A king fish! 👑🐟" },
  { q: "Why did the balloon go near the needle?", a: "pop", display: "It wanted to pop in! 🎈" },
  { q: "What do you call a cat that likes to swim?", a: "catfish", display: "A catfish! 🐱🐟" },
  { q: "Why did the lion eat the tightrope walker?", a: "want a balanced meal", display: "He wanted a balanced meal! 🦁" },
  { q: "What do you call a frog that's illegally parked?", a: "toad", display: "Toad! 🐸" },
  { q: "Why did the duck get arrested?", a: "selling quack", display: "For selling quack! 🦆" },
  { q: "What do you call a dog that meditates?", a: "aware wolf", display: "Aware wolf! 🐕🧘" },
  { q: "Why did the robber take a bath?", a: "make clean getaway", display: "To make a clean getaway! 🛁" },
  { q: "What do you call a can opener that doesn't work?", a: "can't opener", display: "A can't opener! 🥫" },
  { q: "Why did the belt go to jail?", a: "holding up pants", display: "For holding up a pair of pants! 👖" },
  { q: "What do you call a rabbit with fleas?", a: "bugs bunny", display: "Bugs Bunny! 🐰" },
  { q: "Why did the stadium get hot?", a: "fans left", display: "All the fans left! 🏟️" },
];

export const riddles = [
  { q: "I have hands but can't clap. What am I?", a: "clock", display: "A clock! ⏰" },
  { q: "What has ears but cannot hear?", a: "corn", display: "Corn! 🌽" },
  { q: "What gets wetter the more it dries?", a: "towel", display: "A towel! 🛁" },
  { q: "What can you catch but not throw?", a: "cold", display: "A cold! 🤧" },
  { q: "What has legs but doesn't walk?", a: "table", display: "A table! 🪑" },
  { q: "What goes up but never comes down?", a: "age", display: "Your age! 🎂" },
  { q: "I'm tall when I'm young and short when I'm old. What am I?", a: "candle", display: "A candle! 🕯️" },
  { q: "What has a head and a tail but no body?", a: "coin", display: "A coin! 🪙" },
  { q: "What has to be broken before you can use it?", a: "egg", display: "An egg! 🥚" },
  { q: "I have cities, but no houses. I have mountains, but no trees. I have water, but no fish. What am I?", a: "map", display: "A map! 🗺️" },
  { q: "What can travel around the world while staying in a corner?", a: "stamp", display: "A stamp! 📬" },
  { q: "What has many keys but can't open a single lock?", a: "piano", display: "A piano! 🎹" },
  { q: "What has a neck but no head?", a: "bottle", display: "A bottle! 🍾" },
  { q: "What belongs to you but other people use it more than you?", a: "name", display: "Your name! 🏷️" },
  { q: "What has one eye but can't see?", a: "needle", display: "A needle! 🪡" },
  { q: "What has words but never speaks?", a: "book", display: "A book! 📖" },
  { q: "What runs but never walks, has a mouth but never talks?", a: "river", display: "A river! 🏞️" },
  { q: "What can fill a room but takes up no space?", a: "light", display: "Light! 💡" },
  { q: "I have teeth but can't bite. What am I?", a: "comb", display: "A comb! 🪮" },
  { q: "What has a bottom at the top?", a: "legs", display: "Your legs! 🦵" },
  { q: "What is full of holes but still holds water?", a: "sponge", display: "A sponge! 🧽" },
  { q: "I shave every day but my beard stays the same. What am I?", a: "barber", display: "A barber! ✂️" },
  { q: "What can you break without touching it?", a: "promise", display: "A promise! 🤝" },
  { q: "What goes through cities and fields but never moves?", a: "road", display: "A road! 🛣️" },
  { q: "What building has the most stories?", a: "library", display: "A library! 📚" },
  { q: "What has a face and two hands but no arms or legs?", a: "clock", display: "A clock! ⏰" },
  { q: "What can you hold in your left hand but not in your right?", a: "elbow", display: "Your right elbow! 🦴" },
  { q: "What has a thumb and four fingers but is not alive?", a: "glove", display: "A glove! 🧤" },
  { q: "What gets bigger the more you take away?", a: "hole", display: "A hole! 🕳️" },
  { q: "What kind of coat is always wet when you put it on?", a: "paint", display: "Paint! 🎨" },
  { q: "What has a bark but no bite?", a: "tree", display: "A tree! 🌳" },
  { q: "What begins with T, ends with T, and has T in it?", a: "teapot", display: "A teapot! 🫖" },
  { q: "What has 13 hearts but no other organs?", a: "cards", display: "A deck of cards! 🃏" },
  { q: "What is so fragile that saying its name breaks it?", a: "silence", display: "Silence! 🤫" },
  { q: "What has a bed but never sleeps?", a: "river", display: "A river! 🏞️" },
  { q: "What can you make that no one can see?", a: "noise", display: "Noise! 🔊" },
  { q: "What has an end but no beginning?", a: "stick", display: "A stick! 🪵" },
  { q: "What has a spine but no bones?", a: "book", display: "A book! 📚" },
  { q: "What is black when you buy it, red when you use it, and gray when you throw it away?", a: "charcoal", display: "Charcoal! 🔥" },
  { q: "What has a ring but no finger?", a: "phone", display: "A phone! 📱" },
  { q: "What can you keep after giving to someone?", a: "word", display: "Your word! 💬" },
  { q: "What has hands but can't clap?", a: "clock", display: "A clock! ⏰" },
  { q: "What is always in front of you but can't be seen?", a: "future", display: "The future! 🔮" },
  { q: "What has a tongue but cannot talk?", a: "shoe", display: "A shoe! 👟" },
  { q: "What comes down but never goes up?", a: "rain", display: "Rain! 🌧️" },
  { q: "What has to be taken before you can have it?", a: "picture", display: "A picture! 📸" },
  { q: "What kind of room has no doors or windows?", a: "mushroom", display: "A mushroom! 🍄" },
  { q: "What has four wheels and flies?", a: "garbage truck", display: "A garbage truck! 🚛" },
  { q: "What can you put in a bucket to make it lighter?", a: "hole", display: "A hole! 🪣" },
  { q: "What has a bottom at the top of it?", a: "legs", display: "Your legs! 🦵" },
];

export const motivationalQuotes = [
  { text: "You're braver than you believe, stronger than you seem, and smarter than you think!", author: "Winnie the Pooh" },
  { text: "The more that you read, the more things you will know. The more that you learn, the more places you'll go!", author: "Dr. Seuss" },
  { text: "You're off to great places! Today is your day!", author: "Dr. Seuss" },
  { text: "Always let your conscience be your guide.", author: "Pinocchio" },
  { text: "Even miracles take a little time.", author: "Cinderella" },
  { text: "Just keep swimming!", author: "Dory" },
  { text: "To infinity and beyond!", author: "Buzz Lightyear" },
  { text: "Adventure is out there!", author: "Up" },
  { text: "Ohana means family. Family means nobody gets left behind.", author: "Lilo & Stitch" },
  { text: "The flower that blooms in adversity is the most rare and beautiful of all.", author: "Mulan" },
];

export const wordOfTheDay = [
  // Character & Virtues (Advanced Vocabulary)
  { english: "Magnificent", spanish: "Magnífico", emoji: "✨", pronunciation: "mag-NIF-i-sent" },
  { english: "Extraordinary", spanish: "Extraordinario", emoji: "🌟", pronunciation: "ik-STRAWR-di-ner-ee" },
  { english: "Courageous", spanish: "Valiente", emoji: "🦁", pronunciation: "kuh-RAY-jus" },
  { english: "Perseverance", spanish: "Perseverancia", emoji: "🧗", pronunciation: "per-suh-VEER-uns" },
  { english: "Compassion", spanish: "Compasión", emoji: "💝", pronunciation: "kum-PASH-un" },
  { english: "Integrity", spanish: "Integridad", emoji: "⚖️", pronunciation: "in-TEG-ri-tee" },
  { english: "Determination", spanish: "Determinación", emoji: "🎯", pronunciation: "di-ter-mi-NAY-shun" },
  { english: "Gratitude", spanish: "Gratitud", emoji: "🙏", pronunciation: "GRAT-i-tood" },
  { english: "Resilience", spanish: "Resiliencia", emoji: "🌱", pronunciation: "ri-ZIL-yuns" },
  { english: "Empathy", spanish: "Empatía", emoji: "💙", pronunciation: "EM-puh-thee" },
  { english: "Bravery", spanish: "Valentía", emoji: "🦸", pronunciation: "BRAY-vuh-ree" },
  { english: "Generosity", spanish: "Generosidad", emoji: "🎁", pronunciation: "jen-uh-ROS-i-tee" },
  { english: "Wisdom", spanish: "Sabiduría", emoji: "📜", pronunciation: "WIZ-dum" },
  { english: "Patience", spanish: "Paciencia", emoji: "⏳", pronunciation: "PAY-shuns" },
  { english: "Creativity", spanish: "Creatividad", emoji: "🎨", pronunciation: "kree-ay-TIV-i-tee" },
  
  // Nature & Science (Advanced)
  { english: "Ecosystem", spanish: "Ecosistema", emoji: "🌿", pronunciation: "EE-koh-sis-tum" },
  { english: "Photosynthesis", spanish: "Fotosíntesis", emoji: "🌱", pronunciation: "foh-toh-SIN-thuh-sis" },
  { english: "Constellation", spanish: "Constelación", emoji: "✨", pronunciation: "kon-stel-LAY-shun" },
  { english: "Symmetry", spanish: "Simetría", emoji: "🔷", pronunciation: "SIM-i-tree" },
  { english: "Volcano", spanish: "Volcán", emoji: "🌋", pronunciation: "vol-KAY-noh" },
  { english: "Galaxy", spanish: "Galaxia", emoji: "🌌", pronunciation: "GAL-uk-see" },
  { english: "Hibernate", spanish: "Hibernar", emoji: "🐻", pronunciation: "HY-ber-nayt" },
  { english: "Camouflage", spanish: "Camuflaje", emoji: "🦎", pronunciation: "KAM-uh-flahzh" },
  { english: "Metamorphosis", spanish: "Metamorfosis", emoji: "🦋", pronunciation: "met-uh-MOR-fuh-sis" },
  { english: "Nebula", spanish: "Nebulosa", emoji: "🌠", pronunciation: "NEB-yoo-luh" },
  
  // Big Ideas (Philosophy & Concepts)
  { english: "Infinity", spanish: "Infinito", emoji: "∞", pronunciation: "in-FIN-i-tee" },
  { english: "Perspective", spanish: "Perspectiva", emoji: "🔭", pronunciation: "per-SPEK-tiv" },
  { english: "Harmony", spanish: "Armonía", emoji: "🎵", pronunciation: "HAR-muh-nee" },
  { english: "Serendipity", spanish: "Serendipia", emoji: "🍀", pronunciation: "ser-un-DIP-i-tee" },
  { english: "Curiosity", spanish: "Curiosidad", emoji: "🔍", pronunciation: "kyoo-ree-OS-i-tee" },
  { english: "Possibility", spanish: "Posibilidad", emoji: "🚪", pronunciation: "pos-i-BIL-i-tee" },
  { english: "Adventure", spanish: "Aventura", emoji: "🗺️", pronunciation: "ad-VEN-chur" },
  { english: "Discovery", spanish: "Descubrimiento", emoji: "💡", pronunciation: "di-SKUV-uh-ree" },
  { english: "Imagination", spanish: "Imaginación", emoji: "🌈", pronunciation: "i-maj-i-NAY-shun" },
  { english: "Brilliance", spanish: "Brillantez", emoji: "💎", pronunciation: "BRIL-yuns" },
];
